return {
   empty = require(... .. ".empty"),
   transform = require(... ..".transform"),
   sprite = require(... ..".sprite"),
   playerControls = require(... ..".playerControls"),
   speed = require(... ..".speed"),
   collider = require(... ..".collider"),
   health = require(... ..".health"),
   spells = require(... ..".spells"),
   damage = require(... ..".damage"),
   enemyControls = require(... ..".enemyControls"),
   particle = require(... ..".particle"),
   animation = require(... ..".animation"),
   enemySpawner = require(... ..".enemySpawner"),
}
